#!/usr/bin/env node
// Regenerates employee-directory.seed.json — the provisional/synthetic employee directory
// (TODO(IT-AUTH): replace with GMF IT's real employee table once confirmed, see SRS.md 3.7).
// Run: node tools/generateEmployeeDirectory.js
'use strict';
const fs = require('fs');
const path = require('path');

// 21 real dinas (each files transaction reports, PIC login) + TAB (the reviewing role).
const DINAS_CODES = [
  'TA', 'TB', 'TC', 'TD', 'TE', 'TF', 'TH', 'TI', 'TJ', 'TL', 'TM', 'TMM',
  'TN', 'TP', 'TQ', 'TR', 'TS', 'TU', 'TV', 'TX', 'TZ', 'DFR',
];

function build() {
  const directory = {
    _comment: 'TODO(IT-AUTH): provisional employee directory ONLY, not real GMF employee data — '
      + 'see SRS.md section 3.7. Generated by tools/generateEmployeeDirectory.js, do not hand-edit.',
  };
  for (const code of DINAS_CODES) {
    directory[`demo-${code.toLowerCase()}`] = { dinas: code, role: 'PIC', display_name: `${code} (demo)` };
  }
  directory['demo-tab'] = { dinas: 'TAB', role: 'TAB', display_name: 'TAB (demo)' };
  return directory;
}

function toFileText(directory) {
  const lines = Object.keys(directory).map((key) => {
    if (key === '_comment') return `  "_comment": ${JSON.stringify(directory[key])}`;
    const e = directory[key];
    return `  "${key}": { "dinas": "${e.dinas}", "role": "${e.role}", "display_name": "${e.display_name}" }`;
  });
  return '{\n' + lines.join(',\n') + '\n}\n';
}

if (require.main === module) {
  const out = path.join(__dirname, '..', 'employee-directory.seed.json');
  fs.writeFileSync(out, toFileText(build()));
  console.log(`Wrote ${out}`);
}

module.exports = { build, DINAS_CODES };
