#!/usr/bin/env node
// Regenerates credentials.seed.json — synthetic demo passwords for the Login page ONLY (never
// real credentials, see TODO(IT-AUTH) in the seed file itself). Kept separate from
// data_user/employee-directory.seed.json on purpose: that file is served publicly via
// GET /api/directory (for @mention autocomplete), so a password living in the same object
// would leak through that endpoint.
// Scheme: lowercase(dinas code) + '123'. Run: node tools/generateCredentials.js
'use strict';
const fs = require('fs');
const path = require('path');
const { DINAS_CODES } = require('../../data_user/tools/generateEmployeeDirectory');

function build() {
  const creds = {
    _comment: 'TODO(IT-AUTH): synthetic/demo passwords only. Generated by tools/generateCredentials.js, '
      + 'do not hand-edit — scheme is lowercase(dinas code) + "123".',
  };
  for (const code of DINAS_CODES) creds[`demo-${code.toLowerCase()}`] = `${code.toLowerCase()}123`;
  creds['demo-tab'] = 'tab123';
  return creds;
}

if (require.main === module) {
  const out = path.join(__dirname, '..', 'src', 'credentials.seed.json');
  fs.writeFileSync(out, JSON.stringify(build(), null, 2) + '\n');
  console.log(`Wrote ${out}`);
}

module.exports = { build };
